### PR TITLE
New tests

### PR DESCRIPTION
**Pull request by mschilli87**
## Working on issue #60:

Adding unit tests to ensure that genes listed as single UTR no internal poly(A) sites have
- [x] a single UTR (_passes_)
- [x] no internal poly(A) sites (_passes_)

---
## edit:

As the single UTR test above failed, I'll add additional tests to figure out what is going on.

These test will ensure that genes listed as single UTR no internal poly(A) sites have
- [x] at least one UTR (_passes_)
- [x] less than two UTRs  (_passes_)

### CODE REVIEW

**Comment by mschilli87** [comment]
There are two issues:
1. The single UTR test **_[failed](https://travis-ci.org/rajewsky-lab/polyA/jobs/137813864#L500-L508)!**_
2. Nevertheless, `unit_test.py` still returns `0`, resulting in a [_positive_ build status](https://travis-ci.org/rajewsky-lab/polyA/jobs/137813864#L516-L546).

I'll investigate the first in more detail & opened #65 for the latter.

**Comment by mschilli87** [comment]
What we know so far:
- [There are **no** single-UTR/no-internal-pAi genes with internal pAi's.](https://travis-ci.org/rajewsky-lab/polyA/jobs/137828210#L459)
- [There **are** single-UTR/no-internal-pAi genes that **don't** have a _single_ UTRs.](https://travis-ci.org/rajewsky-lab/polyA/jobs/137828210#L460)
- [There are **no** single-UTR/no-internal-pAi genes with _multiple_ UTRs.](https://travis-ci.org/rajewsky-lab/polyA/jobs/137828210#L458)

**Comment by nukappa** [comment]
thanks mschilli, it could very well be that the problem is in the list itself (don't remember how and when i derived it). i'll write a small function extracting them directly from the annotation file.

**Comment by nukappa** [comment]
quick and dirty: how about using these one-liners to create new files? when i'll have more time i'll write them in python.
-- extract_single_utr_genes.sh
zcat test_data/Homo_sapiens.GRCh38.84_chr9.gtf.gz | awk '$3 == "three_prime_utr" {print $18}' | sort | uniq -c | awk '$1 == 1 {print $2}' | cut -c2- | sed 's/..$//'
-- extract_genes_with_pAi.sh
awk '{print $4}' test_data/output/pAi_gene.bed | uniq | sort | uniq
-- extract all single UTR genes WITHOUT pAi
comm -23 <(extract_single_utr_genes.sh) <(extract_genes_with_pAi.sh)

**Comment by mschilli87** [comment]
I tried to set this up & it might work but this will require building `test_data/output/pAi_gene.bed` for every unit test which will also need the corresponding FASTA file first.
Do we really want to go there or just update the list manually once now & keep it in the repo for the time being?

**Comment by nukappa** [comment]
no no no! we don't want to go there! 
my motivation was that you inspect the one-liners and if you find them ok just update the list manually and add it to the repo :)

**Comment by mschilli87** [comment]
Once https://github.com/rajewsky-lab/polyA/pull/69/commits/663a9baf81e0f36f86c4f74947ab8b94c99d5b5d is merged to `master`, I'll merge it into here & proceed with updating `test_data/single_utr_no_pAi_genes.txt` as suggested.

**Comment by nukappa** [comment]
cool. i merged the bugfix into the master, everything should be fine now.

**Comment by mschilli87** [comment]
I merged in https://github.com/rajewsky-lab/polyA/pull/72/commits/021f7ec694bde85f079d90796888206348d6b8b9 and [all tests passed now](https://travis-ci.org/rajewsky-lab/polyA/jobs/138075155#L457-L460)!
Thus, pulling this into `master` will finally fix #60.

**Comment by nukappa** [comment]
perfect :) should i test and merge or yo uhave more to commit?

**Comment by mschilli87** [comment]
I labeled 'test & merge to master' & assigned you. ;)

**Comment by nukappa** [comment]
haha ok i missed the "being assigned" part. will do asap

**Pull request merged**
