### PR TITLE
Add lower bound

### PR DESCRIPTION
**Pull request by mschilli87**
Corrected version of #83.

Do agree that we we need the `- 1` as we want to substract a length, which is end-start+1?

### CODE REVIEW

**Comment by mschilli87** [comment]
I don't know why the unit test fails.
Locally, it was passing.
I'll re-run locally without the cached intermediate files & I'll restart the unit test on travis.

**Comment by mschilli87** [comment]
I can confirm: locally it passes, on Travis it fails.

**Comment by nukappa** [comment]
pulling for testing

**Comment by mschilli87** [comment]
As this didn't include the improvments merged with #77, I will rebase this & open a new pull-request after propagating #77 to master.

**Pull request merged**
