### PR TITLE
added build test & code coverage integration

### PR DESCRIPTION
**Pull request by mschilli87**
once this is merged to `master`, it should run `unit_test.py` & generate coverage reports for each commit to `master`

### CODE REVIEW

**Comment by mschilli87** [comment]
As shown above, the build checks already work: https://github.com/rajewsky-lab/polyA/pull/57/commits/6c86171431b51881b42006072a5fac5ff3b5d7f0 failed because `scipy` was missing on the test system, after adding it https://github.com/rajewsky-lab/polyA/pull/57/commits/241ba4a29da29b64bbe67cef84396ad23adaa1f5 worked. Also, the coverage report is already available at https://codecov.io/gh/rajewsky-lab/polyA. Upon merge, both will be linked on top of the readme through status badges.

**Comment by mschilli87** [comment]
## This is how it will look in the README:

## [Build Status](https://travis-ci.org/rajewsky-lab/polyA) [codecov](https://codecov.io/gh/rajewsky-lab/polyA)

The build status is 'unknown' as of now since it refers to the `master` branch which doesn't have these commits yet.

**Comment by nukappa** [comment]
sehr cool! i will test and merge

**Comment by mschilli87** [comment]
Not sure if you can test as I had to setup Travis CI & codecov for this repo. But I'm positive it'll work. I reproduced it in my fork before & then re-wired all the accounts accordingly.

**Comment by nukappa** [comment]
pull request will be merged from the branch to the master, not directly [tested]

**Pull request closed without merging**
